const categories = {
  films: [
    "Reservoir Dogs",
    "Pulp Fiction",
    "Jackie Brown",
    "Kill Bill",
    "Death Proof",
    "Inglorious Basterds",
    "Django Unchained",
    "The Hateful Eight",
    "Once Upon a Time in Hollywood",
    "Lock Stock and Two Smoking Barrels",
    "Snatch",
    "Revolver",
    "RocknRolla",
  ],
  cities: [
    "Hong Kong",
    "Los Angeles",
    "Ulaanbaatar",
    "Casablanca",
    "Honolulu",
    "Vancouver",
    "Barcelona",
    "Birmingham",
    "Edinburgh",
    "Paramaribo",
    "Salamanca",
    "Kuala Lumpur",
    "Rio de Janeiro",
    "Islamabad",
    "Addis Ababa",
    "Dar es Salaam",
    "Antananarivo",
    "Zaragoza",
    "Stockholm",
    "Copenhagen",
    "Pyongyang",
    "Yekaterinburg",
    "Hiroshima",
    "Yokohama",
    "Melbourne",
    "Kinshasa",
    "Brazzaville",
    "Manchester",
    "Bratislava",
    "Guadalajara",
    "Acapulco",
    "Buenos Aires",
    "Montevideo",
    "Santo Domingo",
    "San Francisco",
    "Philadelphia",
  ],
};

module.exports = categories;
